# Generated by Codex on 2026-07-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0067_widen_diary_entry_media_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="filter_metadata_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="imdb_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="letterboxd_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="release_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="rotten_tomatoes_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ItemFilterFacet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facet_type",
                    models.CharField(
                        choices=[("genre", "Genre"), ("language", "Language")],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_facets",
                        to="app.item",
                    ),
                ),
            ],
            options={
                "ordering": ["facet_type", "value"],
            },
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["media_type", "release_year"],
                name="app_item_media_t_967d28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["media_type", "release_date"],
                name="app_item_media_t_6e9177_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["media_type", "letterboxd_rating"],
                name="app_item_media_t_689b1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["media_type", "imdb_rating"],
                name="app_item_media_t_2ba6ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["media_type", "rotten_tomatoes_rating"],
                name="app_item_media_t_cf89d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemfilterfacet",
            index=models.Index(
                fields=["facet_type", "value"],
                name="app_itemfil_facet_t_a66f95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemfilterfacet",
            index=models.Index(
                fields=["item", "facet_type"],
                name="app_itemfil_item_id_ea562c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemfilterfacet",
            constraint=models.UniqueConstraint(
                fields=("item", "facet_type", "value"),
                name="app_itemfilterfacet_unique_item_type_value",
            ),
        ),
    ]
