# Generated by Django 5.2.14 on 2026-07-18 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def initialize_single_weight_state(apps, schema_editor):
    DiaryEntry = apps.get_model("app", "DiaryEntry")
    MediaLike = apps.get_model("app", "MediaLike")

    for model_name, media_type in (("Movie", "movie"), ("Music", "music")):
        Model = apps.get_model("app", model_name)
        duplicate_pairs = (
            Model.objects.values("user_id", "item_id")
            .annotate(total=models.Count("id"))
            .filter(total__gt=1)
        )
        for pair in duplicate_pairs.iterator():
            rows = list(
                Model.objects.filter(
                    user_id=pair["user_id"],
                    item_id=pair["item_id"],
                ).order_by("-created_at", "-id"),
            )
            keeper = rows[0]
            if keeper.score is None:
                keeper.score = next((row.score for row in rows if row.score is not None), None)
            keeper.save(update_fields=["score"])
            Model.objects.filter(id__in=[row.id for row in rows[1:]]).delete()

        diary_pairs = DiaryEntry.objects.filter(item__media_type=media_type).values(
            "user_id",
            "item_id",
        ).distinct()
        for pair in diary_pairs.iterator():
            Model.objects.get_or_create(
                user_id=pair["user_id"],
                item_id=pair["item_id"],
                defaults={"status": "Completed", "progress": 1},
            )

        for tracking in Model.objects.all().iterator():
            entries = DiaryEntry.objects.filter(
                user_id=tracking.user_id,
                item_id=tracking.item_id,
            )
            latest = entries.order_by("-consumed_at", "-id").first()
            has_entries = latest is not None
            tracking.end_date = latest.consumed_at if latest else None
            tracking.direct_consumption = not has_entries and tracking.status == "Completed"
            if has_entries:
                tracking.status = "Completed"
                tracking.progress = 1
            has_like = MediaLike.objects.filter(
                user_id=tracking.user_id,
                item_id=tracking.item_id,
            ).exists()
            tracking.like_is_independent = has_like
            if model_name == "Movie":
                tracking.liked = has_like
                update_fields = ["liked"]
            else:
                update_fields = []
            tracking.save(
                update_fields=[
                    "end_date",
                    "direct_consumption",
                    "status",
                    "progress",
                    "like_is_independent",
                    *update_fields,
                ],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_historicalmusic_music_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['user', 'item', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['user', 'item', '-created_at']},
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='import_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='import_source_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='import_source_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiaryentry',
            name='import_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaldiaryentry',
            name='import_source_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldiaryentry',
            name='import_source_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmovie',
            name='direct_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmovie',
            name='like_is_independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmovie',
            name='like_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='historicalmovie',
            name='rating_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='historicalmusic',
            name='direct_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmusic',
            name='like_is_independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmusic',
            name='like_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='historicalmusic',
            name='rating_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='movie',
            name='direct_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='like_is_independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='like_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='music',
            name='direct_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='like_is_independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='like_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='music',
            name='rating_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.diaryentry'),
        ),
        migrations.RunPython(initialize_single_weight_state, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='diaryentry',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('import_source', ''), _negated=True), models.Q(('import_source_id', ''), _negated=True)), fields=('user', 'import_source', 'import_source_id'), name='app_diary_unique_import_source_record'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='app_movie_unique_user_item'),
        ),
        migrations.AddConstraint(
            model_name='music',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='app_music_unique_user_item'),
        ),
    ]
