# Generated by Django 5.2.14 on 2026-07-21 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_movie_options_alter_music_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_source', models.CharField(max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('vote_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('failed', 'Failed')], max_length=20)),
                ('last_attempted_at', models.DateTimeField()),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=1000)),
                ('item', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='external_ratings', to='app.item')),
            ],
            options={
                'indexes': [models.Index(fields=['rating_source', 'value'], name='app_extrating_source_value_idx'), models.Index(fields=['rating_source', 'status', 'last_attempted_at'], name='app_extrating_scan_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'rating_source'), name='app_extrating_item_source_uniq'), models.CheckConstraint(condition=models.Q(('status__in', ['available', 'unavailable', 'failed'])), name='app_extrating_status_valid'), models.CheckConstraint(condition=models.Q(('value__isnull', True), ('value__gte', 0), _connector='OR'), name='app_extrating_value_nonnegative'), models.CheckConstraint(condition=models.Q(('max_value__isnull', True), ('max_value__gt', 0), _connector='OR'), name='app_extrating_max_positive'), models.CheckConstraint(condition=models.Q(('value__isnull', True), models.Q(('max_value__isnull', False), ('value__lte', models.F('max_value')), ('last_success_at__isnull', False)), _connector='OR'), name='app_extrating_stored_value_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'available'), _negated=True), ('value__isnull', False), _connector='OR'), name='app_extrating_available_valid')],
            },
        ),
    ]
