# Generated by Django 5.2.14 on 2026-07-21 06:30

import django.db.models.deletion
from django.db import migrations, models


COMPLETED = 'Completed'
DROPPED = 'Dropped'
OPEN_STATUSES = ('In progress', 'Paused')
LEGACY_ORIGIN = 'legacy'


def normalize_legacy_book_tracking(apps, schema_editor):
    """Normalize legacy rows before enforcing one open journey per book."""
    Book = apps.get_model('app', 'Book')
    BookSession = apps.get_model('app', 'BookSession')
    HistoricalBookSession = apps.get_model('app', 'HistoricalBookSession')

    # Every row present at migration time predates explicit journey origins.
    BookSession.objects.update(origin=LEGACY_ORIGIN)
    HistoricalBookSession.objects.update(origin=LEGACY_ORIGIN)

    # A legacy manual completion is the only reliable evidence of an undated
    # Read. Do not manufacture a journey, progress, or date for it.
    Book.objects.exclude(status=COMPLETED).update(completed_manually=False)
    Book.objects.filter(
        status=COMPLETED,
        completion_diary_entry_id__isnull=True,
    ).update(completed_manually=True)
    Book.objects.filter(completion_diary_entry_id__isnull=False).update(
        completed_manually=False,
    )

    # Carry the old Book-level completion link onto a completed journey. Prefer
    # a session whose end timestamp is the diary timestamp, then the sole
    # unlinked completed session. When neither is unambiguous, preserve all old
    # rows and create a legacy completed session using the diary's real date.
    linked_books = Book.objects.filter(
        completion_diary_entry_id__isnull=False,
    ).select_related('completion_diary_entry')
    for book in linked_books.iterator():
        diary_entry = book.completion_diary_entry
        already_linked = BookSession.objects.filter(
            completion_diary_entry_id=diary_entry.pk,
        ).first()
        if already_linked is not None:
            continue

        candidates = BookSession.objects.filter(
            related_book_id=book.pk,
            status=COMPLETED,
            completion_diary_entry_id__isnull=True,
        )
        session = candidates.filter(
            end_date=diary_entry.consumed_at,
        ).order_by('-created_at', '-pk').first()
        if session is None and candidates.count() == 1:
            session = candidates.first()
        if session is None:
            session = BookSession.objects.create(
                related_book_id=book.pk,
                status=COMPLETED,
                end_date=diary_entry.consumed_at,
                origin=LEGACY_ORIGIN,
            )

        BookSession.objects.filter(pk=session.pk).update(
            completion_diary_entry_id=diary_entry.pk,
            origin=LEGACY_ORIGIN,
        )

    # The old save hooks could leave multiple open rows. Preserve the newest
    # row and all progress data, while closing older rows as legacy DNF history.
    duplicate_groups = (
        BookSession.objects.filter(status__in=OPEN_STATUSES)
        .values('related_book_id')
        .annotate(open_count=models.Count('pk'))
        .filter(open_count__gt=1)
    )
    for group in duplicate_groups.iterator():
        open_sessions = list(
            BookSession.objects.filter(
                related_book_id=group['related_book_id'],
                status__in=OPEN_STATUSES,
            ).order_by('-created_at', '-pk'),
        )
        stale_ids = [session.pk for session in open_sessions[1:]]
        BookSession.objects.filter(pk__in=stale_ids).update(
            status=DROPPED,
            origin=LEGACY_ORIGIN,
        )

    # A current session is unambiguous only when the Book itself is open and
    # exactly one open legacy row remains. Align that row with the current Book
    # status because legacy Paused changes did not update BookSession.
    Book.objects.update(current_session=None)
    for book in Book.objects.filter(status__in=OPEN_STATUSES).iterator():
        open_sessions = list(
            BookSession.objects.filter(
                related_book_id=book.pk,
                status__in=OPEN_STATUSES,
            ).order_by('-created_at', '-pk')[:2],
        )
        if len(open_sessions) != 1:
            continue
        current_session = open_sessions[0]
        if current_session.status != book.status:
            BookSession.objects.filter(pk=current_session.pk).update(
                status=book.status,
                origin=LEGACY_ORIGIN,
            )
        Book.objects.filter(pk=book.pk).update(
            current_session_id=current_session.pk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_migrate_legacy_external_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.booksession'),
        ),
        migrations.AddField(
            model_name='book',
            name='like_is_independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='like_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='book',
            name='read_override_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='read_override_previous_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='read_override_previous_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.booksession'),
        ),
        migrations.AddField(
            model_name='book',
            name='read_override_previous_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='undated_read_previous_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.booksession'),
        ),
        migrations.AddField(
            model_name='book',
            name='undated_read_previous_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='undated_read_previous_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='undated_read_previous_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booksession',
            name='completion_diary_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_journey', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='booksession',
            name='mutation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booksession',
            name='origin',
            field=models.CharField(choices=[('live', 'Live journey'), ('direct_log', 'Direct log'), ('legacy', 'Legacy')], default='live', max_length=20),
        ),
        migrations.AddField(
            model_name='booksession',
            name='pre_completion_progress',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booksession',
            name='pre_completion_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booksession',
            name='previous_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_sessions', to='app.booksession'),
        ),
        migrations.AddField(
            model_name='booksession',
            name='previous_read_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booksession',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booksession',
            name='previous_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booksession',
            name='progressed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='current_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.booksession'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='like_is_independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='like_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='rating_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='read_override_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='read_override_previous_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='read_override_previous_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.booksession'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='read_override_previous_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='undated_read_previous_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.booksession'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='undated_read_previous_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='undated_read_previous_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='undated_read_previous_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbooksession',
            name='completion_diary_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='historicalbooksession',
            name='mutation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbooksession',
            name='origin',
            field=models.CharField(choices=[('live', 'Live journey'), ('direct_log', 'Direct log'), ('legacy', 'Legacy')], default='live', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbooksession',
            name='pre_completion_progress',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbooksession',
            name='pre_completion_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalbooksession',
            name='previous_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.booksession'),
        ),
        migrations.AddField(
            model_name='historicalbooksession',
            name='previous_read_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbooksession',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalbooksession',
            name='previous_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbooksession',
            name='progressed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(
            normalize_legacy_book_tracking,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='booksession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['In progress', 'Paused'])), fields=('related_book',), name='app_booksession_one_open_journey'),
        ),
        migrations.AddConstraint(
            model_name='booksession',
            constraint=models.UniqueConstraint(condition=models.Q(('mutation_id__isnull', False)), fields=('related_book', 'mutation_id'), name='app_booksession_unique_mutation'),
        ),
        migrations.AddConstraint(
            model_name='booksession',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='app_booksession_dates_ordered'),
        ),
    ]
