# Generated by Django 5.2.14 on 2026-07-23

from django.db import migrations, models


ROWLING_ID = "80626"
PRIMARY_WORKS = {
    "328491": "Harry Potter and the Philosopher's Stone",
    "429306": "Harry Potter and the Chamber of Secrets",
    "376219": "Harry Potter and the Prisoner of Azkaban",
    "383236": "Harry Potter and the Goblet of Fire",
    "428465": "Harry Potter and the Order of the Phoenix",
    "428506": "Harry Potter and the Half-Blood Prince",
    "382143": "Harry Potter and the Deathly Hallows",
    "83094": "Fantastic Beasts and Where to Find Them",
    "213743": "Quidditch Through the Ages",
    "366623": "The Tales of Beedle the Bard",
    "279285": "Harry Potter and the Cursed Child",
    "726775": "Fantastic Beasts and Where to Find Them: The Original Screenplay",
    "44087": "Fantastic Beasts: The Crimes of Grindelwald: The Original Screenplay",
    "183498": "The Cuckoo's Calling",
    "327408": "The Silkworm",
    "302701": "Career of Evil",
    "429973": "Lethal White",
    "431265": "Troubled Blood",
    "510364": "The Ink Black Heart",
    "720120": "The Running Grave",
    "1360139": "The Hallmarked Man",
    "147273": "The Casual Vacancy",
    "288316": "Very Good Lives",
    "486512": "The Ickabog",
    "2606766": "The Christmas Pig",
}
ADDITIONAL_WORKS = {
    "454247": "Harry Potter: The Prequel",
}
HIDDEN_CREDITS = {
    "593194": "Harry Potter and the Chamber of Secrets: Teacher's Guide, with Poster",
    "1623456": "Wizard People, Dear Reader",
}


def seed_rowling_bibliography(apps, schema_editor):
    """Seed the official bibliography from jkrowling.com/writing."""
    BookCreditOverride = apps.get_model("app", "BookCreditOverride")
    rows = [
        BookCreditOverride(
            author_source="hardcover",
            author_id=ROWLING_ID,
            book_source="hardcover",
            book_id=book_id,
            disposition=disposition,
            display_title=title,
            note="J.K. Rowling official writing bibliography, accessed 2026-07-23.",
        )
        for disposition, works in (
            ("primary", PRIMARY_WORKS),
            ("additional", ADDITIONAL_WORKS),
            ("hidden", HIDDEN_CREDITS),
        )
        for book_id, title in works.items()
    ]
    BookCreditOverride.objects.bulk_create(rows, ignore_conflicts=True)


def remove_rowling_bibliography(apps, schema_editor):
    BookCreditOverride = apps.get_model("app", "BookCreditOverride")
    BookCreditOverride.objects.filter(
        author_source="hardcover",
        author_id=ROWLING_ID,
        book_source="hardcover",
        book_id__in=[*PRIMARY_WORKS, *ADDITIONAL_WORKS, *HIDDEN_CREDITS],
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0075_book_current_session_book_like_is_independent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCreditOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_source",
                    models.CharField(
                        choices=[
                            ("tmdb", "The Movie Database"),
                            ("mal", "MyAnimeList"),
                            ("mangaupdates", "MangaUpdates"),
                            ("igdb", "Internet Game Database"),
                            ("openlibrary", "Open Library"),
                            ("hardcover", "Hardcover"),
                            ("comicvine", "Comic Vine"),
                            ("musicbrainz", "MusicBrainz"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("author_id", models.CharField(max_length=36)),
                (
                    "book_source",
                    models.CharField(
                        choices=[
                            ("tmdb", "The Movie Database"),
                            ("mal", "MyAnimeList"),
                            ("mangaupdates", "MangaUpdates"),
                            ("igdb", "Internet Game Database"),
                            ("openlibrary", "Open Library"),
                            ("hardcover", "Hardcover"),
                            ("comicvine", "Comic Vine"),
                            ("musicbrainz", "MusicBrainz"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("book_id", models.CharField(max_length=36)),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("primary", "Primary work"),
                            ("additional", "Additional work"),
                            ("hidden", "Hidden"),
                        ],
                        max_length=20,
                    ),
                ),
                ("display_title", models.CharField(blank=True, default="", max_length=255)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "ordering": [
                    "author_source",
                    "author_id",
                    "display_title",
                    "book_id",
                ],
                "indexes": [
                    models.Index(
                        fields=["author_source", "author_id"],
                        name="app_bookcredit_author_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "author_source",
                            "author_id",
                            "book_source",
                            "book_id",
                        ),
                        name="app_bookcreditoverride_unique_credit",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            seed_rowling_bibliography,
            remove_rowling_bibliography,
        ),
    ]
