# Generated by Django 5.2.14 on 2026-07-31 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_bookcreditoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('tmdb', 'The Movie Database'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('igdb', 'Internet Game Database'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('comicvine', 'Comic Vine'), ('musicbrainz', 'MusicBrainz'), ('manual', 'Manual')], max_length=20)),
                ('series_id', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('music', 'Music')], max_length=10)),
                ('name', models.TextField()),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MediaSeriesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_memberships', to='app.item')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app.mediaseries')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mediaseries',
            name='items',
            field=models.ManyToManyField(related_name='media_series', through='app.MediaSeriesItem', to='app.item'),
        ),
        migrations.AddConstraint(
            model_name='mediaseriesitem',
            constraint=models.UniqueConstraint(fields=('series', 'item'), name='app_mediaseriesitem_member_uniq'),
        ),
        migrations.AddConstraint(
            model_name='mediaseries',
            constraint=models.UniqueConstraint(fields=('source', 'media_type', 'series_id'), name='app_mediaseries_identity_uniq'),
        ),
    ]
