# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_customlist_is_ranked"),
    ]

    operations = [
        migrations.AddField(
            model_name="customlist",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
