# Generated by Django 5.2.14 on 2026-07-28 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0076_bookcreditoverride"),
        ("lists", "0007_customlist_featured_import"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("tmdb", "The Movie Database"),
                            ("hardcover", "Hardcover"),
                            ("openlibrary", "Open Library"),
                            ("musicbrainz", "MusicBrainz"),
                            ("mal", "MyAnimeList"),
                            ("mangaupdates", "MangaUpdates"),
                            ("anilist", "AniList"),
                        ],
                        max_length=32,
                    ),
                ),
                ("person_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "profile_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                (
                    "known_for_department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": [
                    models.OrderBy(models.F("position"), nulls_last=True),
                    "date_added",
                    "id",
                ],
            },
        ),
        migrations.AddField(
            model_name="customlist",
            name="list_type",
            field=models.CharField(
                choices=[("media", "Media"), ("people", "People")],
                db_default="media",
                default="media",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="customlist",
            constraint=models.CheckConstraint(
                condition=models.Q(("list_type__in", ["media", "people"])),
                name="lists_customlist_valid_list_type",
            ),
        ),
        migrations.AddField(
            model_name="personlistitem",
            name="custom_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_items",
                to="lists.customlist",
            ),
        ),
        migrations.AddConstraint(
            model_name="personlistitem",
            constraint=models.UniqueConstraint(
                fields=("custom_list", "source", "person_id"),
                name="lists_personlistitem_unique_person_list",
            ),
        ),
    ]
