# Generated by Django 5.2.14 on 2026-07-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_historicalmusic_music_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0058_user_profile_backdrop_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='last_search_type_valid',
        ),
        migrations.AddField(
            model_name='user',
            name='hof_music',
            field=models.ForeignKey(blank=True, help_text='Hall of Fame music', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.item'),
        ),
        migrations.AddField(
            model_name='user',
            name='music_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='music_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='music_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='music_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('music', 'Music')], default='tv', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('last_search_type__in', ['tv', 'movie', 'anime', 'manga', 'game', 'book', 'comic', 'music'])), name='last_search_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('music_layout__in', ['grid', 'table'])), name='music_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('music_sort__in', ['score', 'title', 'progress', 'start_date', 'end_date'])), name='music_sort_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('music_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped'])), name='music_status_valid'),
        ),
    ]
